server:
  port: 8088

spring:
  application:
    name: my-restful-service
  messages:
    basename: messages
  # springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null 예외 해결을 위한 조치
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.springframework: debug