server:
  port: 8088

spring:
  application:
    name: my-restful-service
  messages:
    basename: messages
  # springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null 예외 해결을 위한 조치
  security:
    user:
      name: username
      password: passw0rd

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"